"""Generate configs and sbatch files for the landmark hyperparameter grid search.

Grid: model size (small/base/large) x lambda_coord x num_points, everything
else fixed (lambda_focal pinned to 1.0 since only the coord/focal ratio
matters under AdamW).

Example:
    python tools/grid_search.py --output-root exp/landmark --name grid_v1

creates:
    exp/landmark/grid_v1/
        configs/<exp>.py      one config per grid point
        sbatch/<exp>.sbatch   one single-GPU sbatch per grid point
        logs/                 slurm stdout/stderr
        submit_all.sh         sbatch everything
        manifest.csv          grid point -> config/sbatch paths
        <exp>/                training outputs (created by the runs, so wandb
                              runs are named "<grid_name>/<exp_name>")

Once the runs are done (or while they are still going), aggregate the results
into <grid_root>/summary.csv, ranked by best validation mAP:
    python tools/grid_search.py --collect exp/landmark/grid_v1

Per experiment the summary reports the epoch with the best val mAP (with all
val challenge metrics and the test mAP/mAR at that same epoch) plus the
last scored epoch, reading the challenge_scores.jsonl files that the
LandmarkChallengeScorer hook writes into each run directory.
"""

import argparse
import csv
import json
from itertools import product
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

MODEL_SIZES = ("small", "base", "large")
DEFAULT_LAMBDA_COORD = (0.25, 0.5, 1.0, 2.0, 4.0)
DEFAULT_NUM_POINTS = (8192, 16384)
DEFAULT_FOLD = (
    "/homes/mlugli/BracketPrediction/Teeth3DS/splits/"
    "3DTeethland_challenge_train_validation_test_split"
)

# fixed for the whole grid
FIXED_MODEL_PARAMS = dict(
    lambda_focal=1.0,
    nms_radius=1.0,
    score_threshold=0.15,
    max_predictions_per_class=64,
)

CONFIG_TEMPLATE = '''"""Auto-generated by tools/grid_search.py -- do not edit by hand."""

_base_ = ["{base_config}"]

save_path = "{save_path}"
num_worker = {num_worker}
num_points = {num_points}
fold = "{fold}"

model = dict(
    lambda_coord={lambda_coord},
    lambda_focal={lambda_focal},
    nms_radius={nms_radius},
    score_threshold={score_threshold},
    max_predictions_per_class={max_predictions_per_class},
)

data = dict(
    train=dict(num_points=num_points, fold=fold),
    val=dict(num_points=num_points, fold=fold),
    test=dict(num_points=num_points, fold=fold),
)
'''

SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH --job-name={exp_name}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --gres=gpu:1
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time}
#SBATCH --mem={mem}
#SBATCH --output={log_dir}/{exp_name}_%j.out
#SBATCH --error={log_dir}/{exp_name}_%j.err

cd {repo_root} || exit 1

source {repo_root}/.venv/bin/activate
export PYTHONPATH=./

python tools/train.py \\
  --config-file {config_path} \\
  --num-gpus 1
"""

SUBMIT_ALL_TEMPLATE = """#!/bin/bash
# Submit every grid-search job. Generated by tools/grid_search.py.
cd "$(dirname "$0")" || exit 1
for f in sbatch/*.sbatch; do
    sbatch "$f"
done
"""


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--collect",
        metavar="GRID_ROOT",
        help="aggregate an existing grid's results into <GRID_ROOT>/summary.csv "
        "instead of generating a new grid",
    )
    parser.add_argument(
        "--output-root",
        help="folder the grid directory is created in, e.g. exp/landmark "
        "(required unless --collect is used)",
    )
    parser.add_argument(
        "--name",
        default="landmark_grid",
        help="name of the grid directory (also the wandb run name prefix)",
    )
    parser.add_argument(
        "--models", nargs="+", default=list(MODEL_SIZES), choices=MODEL_SIZES
    )
    parser.add_argument(
        "--lambda-coord", nargs="+", type=float, default=list(DEFAULT_LAMBDA_COORD)
    )
    parser.add_argument(
        "--num-points", nargs="+", type=int, default=list(DEFAULT_NUM_POINTS)
    )
    parser.add_argument("--fold", default=DEFAULT_FOLD)
    parser.add_argument("--num-worker", type=int, default=4)
    parser.add_argument("--cpus", type=int, default=4)
    parser.add_argument("--mem", default="30GB")
    parser.add_argument("--time", default="24:00:00")
    parser.add_argument("--account", default="grana_maxillo")
    parser.add_argument("--partition", default="all_usr_prod")
    return parser.parse_args()


def read_scores(run_dir):
    """Read a run's challenge_scores.jsonl into {split: {epoch: scores}}.

    Later records win for a repeated (split, epoch), which dedupes evals
    replayed after a resume.
    """
    scores_path = Path(run_dir) / "challenge_scores.jsonl"
    per_split = {}
    if not scores_path.is_file():
        return per_split
    with open(scores_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            split, epoch = record.pop("split"), record.pop("epoch")
            per_split.setdefault(split, {})[epoch] = record
    return per_split


def collect(grid_root):
    grid_root = Path(grid_root).resolve()
    manifest_path = grid_root / "manifest.csv"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"not a grid directory (no manifest.csv): {grid_root}")
    with open(manifest_path) as f:
        manifest = list(csv.DictReader(f))

    summary_rows = []
    for exp in manifest:
        row = {key: exp[key] for key in ("exp_name", "model", "lambda_coord", "num_points")}
        per_split = read_scores(exp["save_path"])
        val, test = per_split.get("val", {}), per_split.get("test", {})
        if not val:
            row["status"] = "no_scores"
            summary_rows.append(row)
            continue
        best_epoch = max(val, key=lambda epoch: val[epoch]["mAP"])
        last_epoch = max(val)
        row.update(
            status="ok",
            epochs_scored=len(val),
            best_epoch=best_epoch,
            val_mAP=round(val[best_epoch]["mAP"], 4),
            val_mAR=round(val[best_epoch]["mAR"], 4),
            test_mAP=round(test[best_epoch]["mAP"], 4) if best_epoch in test else None,
            test_mAR=round(test[best_epoch]["mAR"], 4) if best_epoch in test else None,
            **{
                f"val_{key}": round(value, 4)
                for key, value in val[best_epoch].items()
                if key not in ("mAP", "mAR")
            },
            last_epoch=last_epoch,
            val_mAP_last=round(val[last_epoch]["mAP"], 4),
            val_mAR_last=round(val[last_epoch]["mAR"], 4),
            test_mAP_last=round(test[last_epoch]["mAP"], 4) if last_epoch in test else None,
            test_mAR_last=round(test[last_epoch]["mAR"], 4) if last_epoch in test else None,
        )
        summary_rows.append(row)

    summary_rows.sort(key=lambda r: r.get("val_mAP", -1.0), reverse=True)
    fieldnames = max((list(r.keys()) for r in summary_rows), key=len)
    summary_path = grid_root / "summary.csv"
    with open(summary_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(summary_rows)

    scored = sum(1 for r in summary_rows if r.get("status") == "ok")
    print(f"wrote {summary_path} ({scored}/{len(summary_rows)} experiments with scores)")


def main():
    args = parse_args()

    if args.collect:
        collect(args.collect)
        return
    if not args.output_root:
        raise SystemExit("--output-root is required unless --collect is used")

    grid_root = (Path(args.output_root) / args.name).resolve()
    config_dir = grid_root / "configs"
    sbatch_dir = grid_root / "sbatch"
    log_dir = grid_root / "logs"
    for d in (config_dir, sbatch_dir, log_dir):
        d.mkdir(parents=True, exist_ok=True)

    fold = Path(args.fold)
    if not fold.is_dir():
        raise FileNotFoundError(f"fold folder not found: {fold}")

    manifest_rows = []
    for size, lambda_coord, num_points in product(
        args.models, args.lambda_coord, args.num_points
    ):
        base_config = REPO_ROOT / "configs/teeth3ds" / f"landmark-litept-{size}.py"
        if not base_config.is_file():
            raise FileNotFoundError(f"base config not found: {base_config}")

        exp_name = f"{size}_lc{lambda_coord:g}_np{num_points}"
        config_path = config_dir / f"{exp_name}.py"
        sbatch_path = sbatch_dir / f"{exp_name}.sbatch"

        config_path.write_text(
            CONFIG_TEMPLATE.format(
                base_config=base_config,
                save_path=grid_root / exp_name,
                num_worker=args.num_worker,
                num_points=num_points,
                fold=fold,
                lambda_coord=lambda_coord,
                **FIXED_MODEL_PARAMS,
            )
        )
        sbatch_path.write_text(
            SBATCH_TEMPLATE.format(
                exp_name=exp_name,
                cpus=args.cpus,
                account=args.account,
                partition=args.partition,
                time=args.time,
                mem=args.mem,
                log_dir=log_dir,
                repo_root=REPO_ROOT,
                config_path=config_path,
            )
        )
        manifest_rows.append(
            dict(
                exp_name=exp_name,
                model=size,
                lambda_coord=lambda_coord,
                num_points=num_points,
                save_path=grid_root / exp_name,
                config=config_path,
                sbatch=sbatch_path,
            )
        )

    manifest_path = grid_root / "manifest.csv"
    with open(manifest_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(manifest_rows[0].keys()))
        writer.writeheader()
        writer.writerows(manifest_rows)

    submit_all = grid_root / "submit_all.sh"
    submit_all.write_text(SUBMIT_ALL_TEMPLATE)
    submit_all.chmod(0o755)

    print(f"grid root: {grid_root}")
    print(
        f"generated {len(manifest_rows)} experiments "
        f"({len(args.models)} models x {len(args.lambda_coord)} lambda_coord "
        f"x {len(args.num_points)} num_points)"
    )
    print(f"submit with: bash {submit_all}")


if __name__ == "__main__":
    main()
